[versions]
agp = "8.5.0"
desugar = "2.0.4"
kotlin = "1.9.0"
okhttp = "4.12.0"
coreKtx = "1.13.1"
kotlinxCoro = "1.8.0"

[libraries]
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoro" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

